I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 94, in script
    with pixlellate
  File "game/script.rpy", line 94, in <module>
    with pixlellate
NameError: name 'pixlellate' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 94, in script
    with pixlellate
  File "C:\Users\Akatsurame\Documents\Programing\renpy-8.1.3-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Akatsurame\Documents\Programing\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Akatsurame\Documents\Programing\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 94, in <module>
    with pixlellate
NameError: name 'pixlellate' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
YL往事 alpha 0.1
Sat Nov 25 02:55:16 2023
